version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./candidate.sql:/docker-entrypoint-initdb.d/candidate.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=service-for-cv
    networks:
      - backend
  app:
    container_name: app
    image: alexkuznechik/serviceforcv
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - spring.datasource.url=jdbc:postgresql://db:5432/service-for-cv
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
    driver: bridge